[device]
name = "avant-eval-board"
#family = ""
part = "lav-at-500e-3lfg1156c"
board = ""

[resources]
# they have 7 512kb blocks also
DSP   = 156
BRAM  = 208
FF    = 198000 # ????
LUT   =  96000

[system]
board_frequency = 200 # in MHz
memory_bandwidth = 16.8 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 128
