[device]
name = "KV260"
#family = ""
part = "xc7z020clg484-1"
board = "xilinx.com:zc702:part0:1.4"

[resources]
DSP   = 1200
BRAM  = 288
URAM  = 64
FF    = 512000
LUT   = 256000

[system]
board_frequency = 200 # in MHz
memory_bandwidth = 100.0 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 128
