[device]
name = "u200"
part = "xcu200-fsgd2104-2-e"
board = "xilinx.com:au200:part0:1.3"

[resources]
DSP   = 6840
BRAM  = 4320
FF    = 2364000
LUT   = 1182000
URAM  = 960

[system]
board_frequency = 250 # in MHz
memory_bandwidth = 614.4 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 512

[ethernet]
bandwidth = 100.0 # in Gbps
latency = 0.000005 # in seconds