[device]
name = "u250"
part = "xc7z020clg484-1"
board = "xilinx.com:zc702:part0:1.4"

[resources]
DSP   = 12288
BRAM  = 5376
FF    = 3456000
LUT   = 1728000
URAM  = 1280

[system]
board_frequency = 200 # in MHz
memory_bandwidth = 100.0 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 512

