[device]
name = "vc707"
#family = ""
part = "xc7vx485tffg1761c"
board = "" #TODO: add board file

[resources]
DSP   = 2800
BRAM  = 1030
FF    = 607200
LUT   = 303600

[system]
board_frequency = 200 # in MHz
memory_bandwidth = 102.4 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 128
