[device]
name = "zc706"
#family = ""
part = "xc7z045ffg900-2"
board = "xilinx.com:zc706:part0:1.4"

[resources]
DSP   = 900
BRAM  = 545
FF    = 437200
LUT   = 218600

[system]
board_frequency = 200 # in MHz
memory_bandwidth = 100.0 # in Gbps
reconfiguration_time = 0.08255 # in seconds
port_width = 128
