[device]
name = "zcu102"
#family = ""
part = "xczu7ev-ffvb1156-2-e"
board = "" #TODO: add board file

[resources]
DSP   = 1728
BRAM  = 624
FF    = 504000
LUT   = 461000

[system]
board_frequency = 160 # in MHz
memory_bandwidth = 135.83 # in Gbps
reconfiguration_time = 0.08255 # in seconds
axi_ports = 2
axi_data_width = 128
