[general]
logging = false
checkpoints = false
resource_allocation = 0.90
bram_to_lut = true
off_chip_streaming = true
balance_bram_uram = true

[transforms.fine]
apply_transform = true
probability = 0.35
start_complete = false

[transforms.coarse]
apply_transform = true
probability = 0.35

[transforms.weights_reloading]
apply_transform = true
probability = 0.30
start_max = true

[transforms.partition]
apply_transform = false
probability = 0.25
start_complete = true
allowed_type = ["split", "merge"]
allowed_partitions = [
    # ["*", "*"],
    ["Add", "*"],
    ["*", "Relu"],
    ["Mul", "*"],
]
vertical = true
allowed_single_layer_merge_pre = ["Split", "Relu", "LeakyRelu", "ThresholdedRelu", "Sigmoid", "HardSwish"]
allowed_single_layer_merge_post = ["Concat", "Add", "Mul"]

[annealing]
T = 10.0
T_min = 0.0001
k = 10.0
cool = 0.98
# transform_iterations = 15
