name: fpgaconvnet
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _pytorch_select=0.2
  - blas=1.0
  - ca-certificates=2020.12.8
  - certifi=2020.12.5
  - cffi=1.14.4
  - cudatoolkit=10.0.130
  - cudnn=7.6.5
  - decorator=4.4.2
  - freetype=2.10.4
  - intel-openmp=2020.2
  - jpeg=9b
  - lcms2=2.11
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libprotobuf=3.13.0.1
  - libstdcxx-ng=9.1.0
  - libtiff=4.1.0
  - lz4-c=1.9.2
  - mkl=2020.2
  - mkl-service=2.3.0
  - mkl_fft=1.2.0
  - mkl_random=1.1.1
  - ncurses=6.2
  - networkx=2.5
  - ninja=1.10.2
  - numpy=1.19.2
  - numpy-base=1.19.2
  - olefile=0.46
  - openssl=1.1.1i
  - pillow=8.1.0
  - pip=20.3.3
  - protobuf=3.13.0.1
  - pycparser=2.20
  - python=3.6.12
  - pytorch=1.3.1
  - pyyaml=5.3.1
  - readline=8.0
  - scipy=1.5.2
  - setuptools=51.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - torchvision=0.4.2
  - wheel=0.36.2
  - xz=5.2.5
  - yaml=0.2.5
  - zlib=1.2.11
  - zstd=1.4.5
  - pip:
    - onnx==1.8.0
    - onnxruntime==1.6.0
    - typing-extensions==3.7.4.3
