[general]
logging = false
checkpoints = false
starting_point_distillation = false
resource_allocation = 0.95

[transforms.fine]
apply_transform = false
probability = 0.25
start_complete = true

[transforms.coarse]
apply_transform = true
probability = 0.25

[transforms.weights_reloading]
apply_transform = false
probability = 0.25
start_max = false

[transforms.partition]
apply_transform = false
probability = 0.25
start_complete = false
allowed_partitions = [
    ["Relu", "Conv"],
    ["MaxPool", "Conv"],
    ["Relu", "Gemm"],
    ["AveragePool", "Gemm"]
]

[annealing]
T = 10.0
T_min = 0.001
k = 10.0
cool = 0.95
iterations = 50
