[general]
logging = false
checkpoints = false
starting_point_distillation = false
resource_allocation = 0.90

[transforms.fine]
apply_transform = true
probability = 0.25
start_complete = false

[transforms.coarse]
apply_transform = true
probability = 0.25

[transforms.weights_reloading]
apply_transform = true
probability = 0.25
start_max = true

[transforms.partition]
apply_transform = true
probability = 0.25
start_complete = true
allowed_type = ["split", "merge"]
allowed_partitions = [
    ["*", "*"],
    # ["*", "Split"],
    # ["Concat", "*"],
]
vertical = true
allowed_single_layer_merge = ["Split", "Relu", "LeakyRelu", "ThresholdedRelu"]

[annealing]
T = 10.0
T_min = 0.0001
k = 10.0
cool = 0.98
# transform_iterations = 15
